((matrix-room . "room")
 (matrix-token . "token")
 (matrix-homeserver . "homeserver")
 (nodes . (((node . "tux02")
	    (config . (((app . "genenetwork3")
			(log-file . "/tmp/gn3.log")
			(poll-interval . "100"))
		       ((app . "gn-auth")
			(log-file . "/tmp/gn-auth.log")
			(poll-interval . "100"))
		       ((app . "gn2")
			(log-file . "/tmp/gn2.log")
			(poll-interval . "100"))))))))
